name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - numpy
  - networkx
  - matplotlib
  - scipy
  - ipywidgets
  - pip:
      - ./hiperwalk
